name: Publish

on:
  push:
    branches:
      - main
      - b_v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [17]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Get current version
        id: get_version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Extract patch version
        id: extract_patch
        run: echo ::set-output name=patch_version::${{ steps.get_version.outputs.version }} | awk -F '.' '{print $3}'

      - name: Increase patch version
        id: increase_patch
        run: |
          current_version=$RUNNER_WORKSPACE/$GITHUB_REPOSITORY/target/classes/version.txt
          echo "${{ steps.get_version.outputs.version }}" > $current_version
          new_patch_version=$(( ${{ steps.extract_patch.outputs.patch_version }} + 1 ))
          new_version=$(echo "${{ steps.get_version.outputs.version }}" | sed "s/\(.*\)\.[0-9]*$/\1.$new_patch_version/")
          mvn versions:set -DnewVersion=$new_version

      - name: Build with maven
        run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -U -Prelease -B package deploy --file pom.xml
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
